language: go
sudo: required

go:
- 1.10.1

env:
- BUILD_IMAGE="jaegertracing/jaeger-operator:JOB_${TRAVIS_JOB_NUMBER}"

install:
- "./.travis/install.sh"

script:
- "./.travis/script.sh"

after_success:
- "./.travis/after_success.sh"
