apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-all-in-one-local-storage
spec:
  allInOne:
    volumeMounts:
    - name: data
      mountPath: /badger
    volumes:
    - name: data
      emptyDir: {}
  storage:
    type: badger
    options:
      badger:
        ephemeral: false
        directory-key: "/badger/key"
        directory-value: "/badger/data"
    volumeMounts:
    - name: data
      mountPath: /badger
    volumes:
    - name: data
      emptyDir: {}
